### ISSUE TITLE
Does not build on Ubuntu 22.10

### ISSUE THREAD

**Issue by ijdickinson** [CandyGumdrop/proj#5]
I'm trying to use `proj` on my Ubuntu 22.10 system. When I install `libproj-dev`, I get version 9.0.1:

```sh
$ sudo apt install libproj-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed
  libproj-dev
0 to upgrade, 1 to newly install, 0 to remove and 4 not to upgrade.
Need to get 74.6 kB of archives.
After this operation, 624 kB of additional disk space will be used.
Get:1 http://gb.archive.ubuntu.com/ubuntu kinetic/universe amd64 libproj-dev amd64 9.0.1-1 [74.6 kB]
Fetched 74.6 kB in 0s (1,065 kB/s)   
Selecting previously unselected package libproj-dev:amd64.
(Reading database ... 455228 files and directories currently installed.)
Preparing to unpack .../libproj-dev_9.0.1-1_amd64.deb ...
Unpacking libproj-dev:amd64 (9.0.1-1) ...
Setting up libproj-dev:amd64 (9.0.1-1) ...
```

However, when I try to start my project, it fails because `proj_api.h` is not found:

```sh
 $ iex -S mix
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

src/proj_nif.c:3:10: fatal error: proj_api.h: No such file or directory
 3 | #include <proj_api.h>
|          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:28: src/proj_nif.o] Error 1
```

And, indeed, if I list the contents of `libproj-dev` there is no `proj_api.h`:

```sh
$ dpkg-query -L libproj-dev
/.
/usr
/usr/include
/usr/include/geodesic.h
/usr/include/proj
/usr/include/proj/common.hpp
/usr/include/proj/coordinateoperation.hpp
/usr/include/proj/coordinatesystem.hpp
/usr/include/proj/crs.hpp
/usr/include/proj/datum.hpp
/usr/include/proj/io.hpp
/usr/include/proj/metadata.hpp
/usr/include/proj/nn.hpp
/usr/include/proj/util.hpp
/usr/include/proj.h
/usr/include/proj_constants.h
/usr/include/proj_experimental.h
/usr/include/proj_symbol_rename.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/cmake
/usr/lib/x86_64-linux-gnu/cmake/proj
/usr/lib/x86_64-linux-gnu/cmake/proj/proj-config-version.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj/proj-config.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj/proj-targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj/proj-targets.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj/proj4-targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj/proj4-targets.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj4
/usr/lib/x86_64-linux-gnu/cmake/proj4/proj-targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj4/proj-targets.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj4/proj4-config-version.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj4/proj4-config.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj4/proj4-targets-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/proj4/proj4-targets.cmake
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/proj.pc
/usr/share
/usr/share/doc
/usr/share/doc/libproj-dev
/usr/share/doc/libproj-dev/copyright
/usr/lib/x86_64-linux-gnu/libproj.so
/usr/share/doc/libproj-dev/AUTHORS
/usr/share/doc/libproj-dev/NEWS.Debian.gz
/usr/share/doc/libproj-dev/NEWS.gz
/usr/share/doc/libproj-dev/README
/usr/share/doc/libproj-dev/changelog.Debian.gz
```

Any advice?

**Comment by CandyGumdrop** [comment]
Unfortunately, this library uses the old PROJ.4 API, which has since been completely removed in libproj versions 8 and above.  If there's any way you can install a local build of libproj 7 or older, you should still be able to get this library to work.

I might have a go at rewriting this library to use the new libproj APIs at some point, but I've not really had a need to use this library myself in a while.

**Comment by CandyGumdrop** [comment]
Other than the workaround of using an older build of libproj, this depends on #6

**Comment by ijdickinson** [comment]
OK, thanks for the update. We've had a chat about it in my team, and we think we can defer the SRID conversion until the queries hit the database anyway. So I think it would be great to have an updated version of `proj` for people doing geo-spatial work in Elixir, but it's not an immediately urgent issue for us.
